# Generated by Django 3.1.7 on 2021-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Ông'), ('F', 'Bà')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
