# Generated by Django 3.1.7 on 2021-04-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('gender', models.CharField(choices=[('M', 'Ông'), ('F', 'Bà')], max_length=1, verbose_name='Giới tính')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Địa chỉ')),
                ('email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thiết bị')),
                ('model', models.CharField(max_length=50)),
                ('year_of_manufacture', models.DateField(verbose_name='Năm sản xuất')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.customer')),
                ('device', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.device')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.staff')),
            ],
        ),
    ]
