# Generated by Django 3.1.7 on 2021-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20210502_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(choices=[('P', 'Chưa hoàn thành'), ('F', 'Hoàn thành')], default='P', max_length=1, verbose_name='Trạng thái'),
        ),
    ]
