# Generated by Django 3.1.7 on 2021-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210503_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=None, verbose_name='Ngày giao hàng'),
            preserve_default=False,
        ),
    ]
