# Generated by Django 3.1.7 on 2021-05-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20210508_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email_notify',
            field=models.BooleanField(default=False, verbose_name='Gửi thông báo'),
            preserve_default=False,
        ),
    ]
