# Generated by Django 3.1.7 on 2021-05-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20210509_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
