# Generated by Django 3.1.7 on 2021-05-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20210525_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.SmallIntegerField(blank=True, choices=[(73, 'Quảng Bình'), (74, 'Quảng Trị'), (75, 'Thừa Thiên Huế'), (43, 'Đà Nẵng'), (92, 'Quảng Nam'), (76, 'Quảng Ngãi'), (0, 'Khác')]),
        ),
    ]
